spring.application.name=UrlShortner
#spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
#spring.datasource.username=postgres
#spring.datasource.password=bharath0802
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.docker.compose.lifecycle-management=start_only

## App Config
app.baseUrl=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10
